fix/ circular imports after ruff fixes
 python -m pytest .
ImportError while loading conftest 'C:\00_Developer\GitHub\python-can-j1939\conftest.py'.
conftest.py:3: in <module>
    from test.helpers.feeder import Feeder
test\helpers\feeder.py:6: in <module>
    import j1939
j1939\__init__.py:4: in <module>
    from .Dm14Server import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^
j1939\Dm14Server.py:19: in <module>
    class DM14Server:
j1939\Dm14Server.py:179: in DM14Server
    pgn: int = j1939.ParameterGroupNumber.PGN.DM15,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: partially initialized module 'j1939' has no attribute 'ParameterGroupNumber' (most likely due to a circular import)